### ISSUE TITLE
Feature request: Encryption support

### ISSUE THREAD

**Issue by mpibpc-mroose** [bitnami/bitnami-docker-mariadb-galera#12]
A nice to have thing would be encryption for the replication and the database access itself as described in (https://mariadb.com/kb/en/securing-communications-in-galera-cluster/). This would require:
1. some volume where the certificates could be placed
1. some configuration variables for the declaration of the certificates
1. some documentation how to activate the encrypted mode

Encryption is useful  on docker galera cluster spanning over multiple hosts.

**Comment by miguelaeh** [comment]
Hi @mpibpc-mroose ,
Thank you very much for your request, we will add it to our backlog and we will try to add it.
