### ISSUE TITLE
Example 'Setting up a multi-master cluster' not working

### ISSUE THREAD

**Issue by gitsnaf** [bitnami/bitnami-docker-mariadb-galera#14]
Hi,

I'm trying to setup a galera cluster using exact the two docker commands as in the example 'Setting up a multi-master cluster'. But step 2 fails, it cannot connect to 'mariadb-galera-0'.
Output ist:
`...`
`2020-05-25  9:31:16 0 [Note] WSREP: gcomm thread scheduling priority set to other:0`
`2020-05-25  9:31:16 0 [Warning] WSREP: access file(/bitnami/mariadb/data//gvwstate.dat) failed(No such file or directory)`
`2020-05-25  9:31:16 0 [Note] WSREP: restore pc from disk failed`
`2020-05-25  9:31:16 0 [Note] WSREP: GMCast version 0`
`2020-05-25  9:31:16 0 [Note] WSREP: (7b779aa5, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567`
`2020-05-25  9:31:16 0 [Note] WSREP: (7b779aa5, 'tcp://0.0.0.0:4567') multicast: , ttl: 1`
`2020-05-25  9:31:16 0 [Note] WSREP: EVS version 0`
`2020-05-25  9:31:16 0 [Note] WSREP: gcomm: connecting to group 'my_galera', peer 'mariadb-galera:'`
`2020-05-25  9:31:19 0 [Warning] WSREP: no nodes coming from prim view, prim not possible`
`2020-05-25  9:31:19 0 [Note] WSREP: view(view_id(NON_PRIM,7b779aa5,1) memb {
	7b779aa5,0
} joined {
} left {
} partitioned {
})`
`2020-05-25  9:31:19 0 [Warning] WSREP: last inactive check more than PT1.5S ago (PT3.51587S), skipping check`
`2020-05-25  9:31:49 0 [Note] WSREP: view((empty))`
`2020-05-25  9:31:49 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
	 at gcomm/src/pc.cpp:connect():160`
`2020-05-25  9:31:49 0 [ERROR] WSREP: gcs/src/gcs_core.cpp:gcs_core_open():209: Failed to open backend connection: -110 (Connection timed out)`
`2020-05-25  9:31:49 0 [ERROR] WSREP: gcs/src/gcs.cpp:gcs_open():1458: Failed to open channel 'my_galera' at 'gcomm://mariadb-galera': -110 (Connection timed out)`
`2020-05-25  9:31:49 0 [ERROR] WSREP: gcs connect failed: Connection timed out`
`2020-05-25  9:31:49 0 [ERROR] WSREP: wsrep::connect(gcomm://mariadb-galera) failed: 7`
`2020-05-25  9:31:49 0 [ERROR] Aborting`

**Comment by dani8art** [comment]
Hi @gitsnaf , could you try the following? it seems like the guide is missing an environment variable.

```console
$ docker run -d --name mariadb-galera-0 \
  -e MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes \
  -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
  -e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm:// \
  -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
  -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
  -e MARIADB_ROOT_PASSWORD=my_root_password \
  -e MARIADB_USER=my_user \
  -e MARIADB_PASSWORD=my_password \
  -e MARIADB_DATABASE=my_database \
  bitnami/mariadb-galera:latest

$ docker run -d --name mariadb-galera-1 --link mariadb-galera-0:mariadb-galera \
  -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
  -e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-0:4567 \
  -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
  -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
  -e MARIADB_ROOT_PASSWORD=my_root_password \
  bitnami/mariadb-galera:latest
```

**Comment by gitsnaf** [comment]
That fixed the aborting docker conainter. But the output from node 2 does not look like a cluster to me:
`...`
`2020-05-25 15:23:49 0 [Note] WSREP: Flow-control interval: [16, 16]`
`2020-05-25 15:23:49 0 [Note] WSREP: Trying to continue unpaused monitor`
`2020-05-25 15:23:49 0 [Note] WSREP: Restored state OPEN -> JOINED (10)`
`2020-05-25 15:23:49 1 [Note] WSREP: New cluster view: global state: b954e1f8-9e9b-11ea-99a5-1e90e64b4cc6:10, view# 1: Primary, number of nodes: 1, my index: 0, protocol version 3`
`2020-05-25 15:23:49 0 [Note] WSREP: SST complete, seqno: 10`
`2020-05-25 15:23:49 0 [Note] WSREP: Member 0.0 (655570986bae) synced with group.`
`2020-05-25 15:23:49 0 [Note] WSREP: Shifting JOINED -> SYNCED (TO: 10)`
`...`
`2020-05-25 15:23:49 0 [Note] InnoDB: 10.3.23 started; log sequence number 1637241; transaction id 21`
`2020-05-25 15:23:49 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool`
`2020-05-25 15:23:49 0 [Note] InnoDB: Buffer pool(s) load completed at 200525 15:23:49`
`2020-05-25 15:23:49 0 [Note] Plugin 'FEEDBACK' is disabled.`
`2020-05-25 15:23:49 0 [Note] Server socket created on IP: '0.0.0.0'.`
`2020-05-25 15:23:49 0 [Warning] 'proxies_priv' entry '@% root@655570986bae' ignored in --skip-name-resolve mode.`
`2020-05-25 15:23:49 0 [Note] Reading of all Master_info entries succeeded`
`2020-05-25 15:23:49 0 [Note] Added new Master_info '' to hash table`
`2020-05-25 15:23:49 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.`
`Version: '10.3.23-MariaDB-log'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution`
`2020-05-25 15:23:49 1 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.`
`2020-05-25 15:23:49 1 [Note] WSREP: REPL Protocols: 9 (4, 2)`
`2020-05-25 15:23:49 1 [Note] WSREP: Assign initial position for certification: 10, protocol version: 4`
`2020-05-25 15:23:49 0 [Note] WSREP: Service thread queue flushed.`
`2020-05-25 15:23:49 1 [Note] WSREP: GCache history reset: b954e1f8-9e9b-11ea-99a5-1e90e64b4cc6:0 -> b954e1f8-9e9b-11ea-99a5-1e90e64b4cc6:10`
`2020-05-25 15:23:49 1 [Note] WSREP: Synchronized with group, ready for connections`
`2020-05-25 15:23:49 1 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.`

**Comment by dani8art** [comment]
Hi @gitsnaf you are right I forgot to add some env. Could you try this?

```bash
$ docker run -d --name mariadb-galera-0 \
  -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
  -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
  -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
  -e MARIADB_ROOT_PASSWORD=my_root_password \
  -e MARIADB_USER=my_user \
  -e MARIADB_PASSWORD=my_password \
  -e MARIADB_DATABASE=my_database \
  bitnami/mariadb-galera:latest

$ docker run -d --name mariadb-galera-1 --link mariadb-galera-0:mariadb-galera \
  -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
  -e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera:4567,0.0.0.0:4567 \
  -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
  -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
  -e MARIADB_ROOT_PASSWORD=my_root_password \
  bitnami/mariadb-galera:latest
```

**Comment by gitsnaf** [comment]
Looks better. But I'm not 100% sure that the output means the cluster is setup correctly, but I think so. This is the last output from mariadb-galera-0 node:

`...`
`2020-05-26 11:50:51 1 [Note] WSREP: GCache history reset: 22d056b3-9f47-11ea-8e0e-faaf9b7e107b:0 -> 22d056b3-9f47-11ea-8e0e-faaf9b7e107b:13`
`2020-05-26 11:50:51 1 [Note] WSREP: Synchronized with group, ready for connections`
`2020-05-26 11:50:51 1 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.`
`2020-05-26 11:51:16 0 [Note] WSREP: (25fdf09a, 'tcp://0.0.0.0:4567') connection established to 34c21f5f tcp://172.17.0.3:4567`
`2020-05-26 11:51:16 0 [Note] WSREP: (25fdf09a, 'tcp://0.0.0.0:4567') turning message relay requesting on, nonlive peers:`
`2020-05-26 11:51:16 0 [Note] WSREP: declaring 34c21f5f at tcp://172.17.0.3:4567 stable`
`2020-05-26 11:51:16 0 [Note] WSREP: Node 25fdf09a state prim`
`2020-05-26 11:51:16 0 [Note] WSREP: view(view_id(PRIM,25fdf09a,2) memb {
	25fdf09a,0
	34c21f5f,0
} joined {
} left {
} partitioned {
})`
`2020-05-26 11:51:16 0 [Note] WSREP: save pc into disk`
`2020-05-26 11:51:16 0 [Note] WSREP: New COMPONENT: primary = yes, bootstrap = no, my_idx = 0, memb_num = 2`
`2020-05-26 11:51:16 0 [Note] WSREP: STATE_EXCHANGE: sent state UUID: 351027de-9f47-11ea-af5c-cec56d919940`
`2020-05-26 11:51:17 0 [Note] WSREP: STATE EXCHANGE: sent state msg: 351027de-9f47-11ea-af5c-cec56d919940`
`2020-05-26 11:51:17 0 [Note] WSREP: STATE EXCHANGE: got state msg: 351027de-9f47-11ea-af5c-cec56d919940 from 0 (fae412c49834)`
`2020-05-26 11:51:17 0 [Note] WSREP: STATE EXCHANGE: got state msg: 351027de-9f47-11ea-af5c-cec56d919940 from 1 (84111c977730)`
`2020-05-26 11:51:17 0 [Note] WSREP: Quorum results:
	version    = 6,
	component  = PRIMARY,
	conf_id    = 1,
	members    = 1/2 (joined/total),
	act_id     = 13,
	last_appl. = 0,
	protocols  = 0/9/3 (gcs/repl/appl),
	group UUID = 22d056b3-9f47-11ea-8e0e-faaf9b7e107b`
`2020-05-26 11:51:17 0 [Note] WSREP: Flow-control interval: [23, 23]`
`2020-05-26 11:51:17 0 [Note] WSREP: Trying to continue unpaused monitor`
`2020-05-26 11:51:17 1 [Note] WSREP: New cluster view: global state: 22d056b3-9f47-11ea-8e0e-faaf9b7e107b:13, view# 2: Primary, number of nodes: 2, my index: 0, protocol version 3`
`2020-05-26 11:51:17 1 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.`
`2020-05-26 11:51:17 1 [Note] WSREP: REPL Protocols: 9 (4, 2)`
`2020-05-26 11:51:17 1 [Note] WSREP: Assign initial position for certification: 13, protocol version: 4`
`2020-05-26 11:51:17 0 [Note] WSREP: Service thread queue flushed.`
`2020-05-26 11:51:17 0 [Note] WSREP: Member 1.0 (84111c977730) requested state transfer from '*any*'. Selected 0.0 (fae412c49834)(SYNCED) as donor.`
`2020-05-26 11:51:17 0 [Note] WSREP: Shifting SYNCED -> DONOR/DESYNCED (TO: 13)`
`2020-05-26 11:51:17 1 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.`
`2020-05-26 11:51:17 0 [Note] WSREP: Running: 'wsrep_sst_mariabackup --role 'donor' --address '172.17.0.3:4444/xtrabackup_sst//1' --socket '/opt/bitnami/mariadb/tmp/mysql.sock' --datadir '/bitnami/mariadb/data/' --defaults-file '/opt/bitnami/mariadb/conf/my.cnf' --gtid '22d056b3-9f47-11ea-8e0e-faaf9b7e107b:13' --gtid-domain-id '0' --binlog 'mysql-bin' --mysqld-args --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --port=3306 --wsrep_cluster_name=my_galera --wsrep_node_name=fae412c49834 --wsrep_node_address=172.17.0.2 --wsrep_cluster_address=gcomm:// --wsrep_sst_method=mariabackup --wsrep_sst_auth=my_mariabackup_user:my_mariabackup_password'`
`2020-05-26 11:51:17 1 [Note] WSREP: sst_donor_thread signaled with 0`
`WSREP_SST: [INFO] Streaming with xbstream (20200526 11:51:18.198)`
`WSREP_SST: [INFO] Using socat as streamer (20200526 11:51:18.201)`
`WSREP_SST: [INFO] Using /tmp/tmp.Orl9Ngnwsn as innobackupex temporary directory (20200526 11:51:18.212)`
`WSREP_SST: [INFO] Streaming GTID file before SST (20200526 11:51:18.219)`
`WSREP_SST: [INFO] Evaluating mbstream -c ${INFO_FILE} | socat -u stdio TCP:172.17.0.3:4444; RC=( ${PIPESTATUS[@]} ) (20200526 11:51:18.223)`
`WSREP_SST: [INFO] Sleeping before data transfer for SST (20200526 11:51:18.230)`
`2020-05-26 11:51:19 0 [Note] WSREP: (25fdf09a, 'tcp://0.0.0.0:4567') turning message relay requesting off`
`WSREP_SST: [INFO] Streaming the backup to joiner at 172.17.0.3 4444 (20200526 11:51:28.201)`
`WSREP_SST: [INFO] Evaluating /opt/bitnami/mariadb//bin/mariabackup --innobackupex --defaults-file=/opt/bitnami/mariadb/conf/my.cnf     $tmpopts $INNOEXTRA --galera-info --stream=$sfmt $itmpdir 2> /bitnami/mariadb/data//mariabackup.backup.log | socat -u stdio TCP:172.17.0.3:4444; RC=( ${PIPESTATUS[@]} ) (20200526 11:51:28.205)`
`2020-05-26 11:51:29 14 [Note] WSREP: Provider paused at 22d056b3-9f47-11ea-8e0e-faaf9b7e107b:13 (5)`
`2020-05-26 11:51:30 14 [Note] WSREP: resuming provider at 5`
`2020-05-26 11:51:30 14 [Note] WSREP: Provider resumed.`
`2020-05-26 11:51:30 0 [Note] WSREP: 0.0 (fae412c49834): State transfer to 1.0 (84111c977730) complete.`
`2020-05-26 11:51:30 0 [Note] WSREP: Shifting DONOR/DESYNCED -> JOINED (TO: 13)`
`2020-05-26 11:51:30 0 [Note] WSREP: Member 0.0 (fae412c49834) synced with group.`
`2020-05-26 11:51:30 0 [Note] WSREP: Shifting JOINED -> SYNCED (TO: 13)`
`2020-05-26 11:51:30 12 [Note] WSREP: Synchronized with group, ready for connections`
`2020-05-26 11:51:30 12 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.`
`WSREP_SST: [INFO] Total time on donor: 0 seconds (20200526 11:51:30.629)`
`WSREP_SST: [INFO] Cleaning up temporary directories (20200526 11:51:30.636)`
`2020-05-26 11:51:31 0 [Note] WSREP: 1.0 (84111c977730): State transfer from 0.0 (fae412c49834) complete.`
`2020-05-26 11:51:31 0 [Note] WSREP: Member 1.0 (84111c977730) synced with group.`

**Comment by dani8art** [comment]
You could check the status of the cluster like

```bash
$ docker exec -ti mariadb-galera-0 mysql -u root -pmy_root_password -e "SHOW GLOBAL STATUS LIKE 'wsrep_%';" | grep size
| wsrep_cert_index_size         | 0                                    |
| wsrep_cluster_size            | 2                                    |
```

**Comment by gitsnaf** [comment]
Yep, that looks good. Thank you!
