### ISSUE TITLE
Support IPv6 deployment on k8s

### ISSUE THREAD

**Issue by mmencner** [bitnami/bitnami-docker-mariadb-galera#20]
**Description**

Bringing up a galera cluster with IPv6, requires specification of the following config properties:
```
[galera]
wsrep_sst_receive_address="[$NODE_IP]:4444"
wsrep_provider_options="gmcast.listen_addr=tcp://[::]:4567; ist.recv_addr=[$NODE_IP]:4568"
wsrep_node_address="[$NODE_IP]:4567"
wsrep_cluster_address="gcomm://[$NODE_IP],[$NODE2_IP],[$NODE3_IP]"
```

In case of k8s deployment using the following [helm chart](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera), IP addresses of particular nodes can be accessed using the headless service:
```
[galera]
wsrep_cluster_address="gcomm://mariadb-galera-headless.default.svc.cluster.local"
```
That however is not supported by `/opt/bitnami/scripts/libmariadbgalera.sh`, which forces bootstrap on every k8s pod.

**Steps to reproduce the issue:**

1. Deploy helm chart, modifying IPv4 addresses to IPv6.
2. The first k8s pod comes up, while every subsequent one fails and goes into the CrashLoopBackOff state.

**Describe the results you received:**

The first k8s pod comes up, while every subsequent one fails and goes into the CrashLoopBackOff state.

**Describe the results you expected:**

A fully working galera cluster on k8s over IPv6.

**Additional information you deem important (e.g. issue happens only occasionally):**

The following modifications of container startup script allowed to successfully run galera on k8s over IPv6:
```
command:
- bash
- -ec
- |
    {{- $fullname := include "mariadb-galera.fullname" . }}
    {{- $bootstrapFromNode := int .Values.galera.bootstrap.bootstrapFromNode }}
    # Bootstrap from the indicated node
    NODE_ID="${MY_POD_NAME#"{{ $fullname }}-"}"
    NODE_IP=$(ip -6 a show eth0 scope global | sed -e's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d')
    DB_GALERA_SST_METHOD=rsync
    SST_RECV_ADDR="[$NODE_IP]:4444"
    PROVIDER_OPTIONS="gmcast.listen_addr=tcp://[::]:4567; ist.recv_addr=[$NODE_IP]:4568"
    if [[ "$NODE_ID" -eq "{{ $bootstrapFromNode }}" ]]; then
        export MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
        export MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP={{ ternary "yes" "no" .Values.galera.bootstrap.forceSafeToBootstrap }}
    else
        sed -i 's/echo \"$clusterBootstrap\"/echo \"no\"/g' /opt/bitnami/scripts/libmariadbgalera.sh
    fi
    cat <<EOF >> /opt/bitnami/mariadb/conf/my2.cnf
    [galera]
    wsrep_sst_receive_address="$SST_RECV_ADDR"
    wsrep_provider_options="$PROVIDER_OPTIONS"
    wsrep_node_address="[$NODE_IP]:4567"
    EOF
    sed -i 's/--wsrep_node_address=$(get_node_address)/--wsrep_node_address=[$(get_node_address)]:4567/g' /opt/bitnami/scripts/libmariadbgalera.sh
    sed -i 's/MARIADB_DEFAULT_BIND_ADDRESS=\"0.0.0.0\"/MARIADB_DEFAULT_BIND_ADDRESS=\"::\"/g' /opt/bitnami/scripts/mariadb-env.sh
    sed -i 's/bind-address=127.0.0.1/bind-address=::/g' /opt/bitnami/scripts/libmariadbgalera.sh
    sed -i 's/wsrep_sst_method=mariabackup/wsrep_sst_method=rsync/g' /opt/bitnami/scripts/libmariadbgalera.sh
    sed -i 's/MARIADB_GALERA_DEFAULT_SST_METHOD=\"mariabackup\"/MARIADB_GALERA_DEFAULT_SST_METHOD=\"rsync\"/g' /opt/bitnami/scripts/mariadb-env.sh
    sed -i 's/resolveip -s \"$HOSTNAME\"/hostname -i/g' /opt/bitnami/scripts/libmariadbgalera.sh
    PROVIDER_OPTIONS="gmcast.listen_addr=tcp:\/\/[::]:4567; ist.recv_addr=[$NODE_IP]:4568"
    sed -i "s/\"\$EXEC\" \"\${flags\[@\]}\"/\"\$EXEC\" \"\${flags\[@\]}\" \"--wsrep-sst-receive-address=$SST_RECV_ADDR\" \"--wsrep-provider-options=$PROVIDER_OPTIONS\"/g" /opt/bitnami/scripts/mariadb-galera/run.sh
    exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
```

**Comment by dani8art** [comment]
Hi @mmencner thank you so much for your contribution.

Don't you think we should do this in a transparent way? I mean the start up script should not depend on the environment IP protocol version, right? 

Do you know why galera needs the node ips instead of the domain?

**Comment by mmencner** [comment]
Definitely! If we can get the solution generic, that would be better. However, so far that seemed to me like a galera-design decision.

**Comment by dani8art** [comment]
Hi @mmencner this is something would be good to have and I'm going to open an internal task in order to evaluate with the team and prioritize it, unfortunately, we are not able to give you an ETA even we couldn't know if we are going to work on it by now. However, we are open to contributions and suggestion and if you have a chance and you think you can do it, feel free to open a PR with a proposal and we will be very happy to handle it. 

Thank you so much!
Hopefully you finally encouraged and we could work together!

**Comment by mmencner** [comment]
Thanks for getting this merged so quickly!
