### ISSUE TITLE
MariaDB replication user and password are hardcoded

### ISSUE THREAD

**Issue by tommyalatalo** [bitnami/bitnami-docker-mariadb-galera#24]
The container appears to set up the replication user and password hardcoded to "monitor" and "monitor".
There are env vars defined in mariadb-env.sh as MARIADB_REPLICATION_USER and MARIADB_REPLICATION_PASSWORD but they're never used.

This is quite obviously a security flaw in the configuration of this container (tag galera:10.5.5) if this is actually the case.

mysql_ensure_replication_user_exists in libmariadbgalera.sh:
```
mysql_ensure_replication_user_exists() {
    local -r user="${1:?user is required}"
    local -r password="${2:-}"

    debug "Configure replication user"

    if [[ "$DB_FLAVOR" = "mariadb" ]]; then
        mysql_execute "mysql" "$DB_ROOT_USER" "$DB_ROOT_PASSWORD" <<EOF
grant REPLICATION CLIENT ON *.* to '$user'@'%' identified by '$password';
grant PROCESS ON *.* to '$user'@'localhost' identified by '$password';
flush privileges;
EOF
    else
        mysql_execute "mysql" "$DB_ROOT_USER" "$DB_ROOT_PASSWORD" <<EOF
grant REPLICATION CLIENT ON *.* to '$user'@'%' identified with 'mysql_native_password' by '$password';
grant PROCESS ON *.* to '$user'@'localhost' identified with 'mysql_native_password' by '$password';
flush privileges;
EOF
    fi
}
```

only call to mysql_ensure_replication_user_exists is on line 526 in libmariadbgalera.sh, there is no way to override the defaults.
```
mysql_ensure_replication_user_exists "monitor" "monitor"
```

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. I will open a task for investigation and to provide a fix. As soon as we have more news, we will update the ticket.

**Comment by FraPazGal** [comment]
Hi @tommyalatalo,

Like you said, this issue was a bug in our code. We have fixed it and rolled it out in today's release, so now it should work as intended; taking the user and password values from the `ENVs` and only using `monitor/monitor` as default values.

Thanks for reporting this issue and please let us know If you have any other problem.
