### ISSUE TITLE
why mysql user to be used to run my script after run.sh?

### ISSUE THREAD

**Issue by lcfang** [bitnami/bitnami-docker-mariadb-galera#29]
**Description**

**Steps to reproduce the issue:**

1. [First Step] create a configmap for running some scripts after run.sh
2. [Second Step] mount the configmap as file in statefulset
3. [and so on...] install using helm charts

**Describe the results you received:**

**Describe the results you expected:**

the pod can't work, and I got this logs:
```
mariadb 13:11:38.77 INFO  ==> ** Starting MariaDB **
mariadb 13:11:38.77 INFO  ==> Setting previous boot
error: failed switching to "mysql": unable to find user mysql: no matching entries in passwd file
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
10.5.4-debian
- Output of `docker version`:

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 60
  Running: 57
  Paused: 0
  Stopped: 3
 Images: 36
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.4.230-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.67GiB
 Name: node-1
 ID: HIKJ:ZIY5:WHYC:MDUS:HVCQ:P3RD:J6K7:LQSX:722B:7GJ6:AP6W:LJW6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hub.pmlabs.com.cn
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
$ helm  version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
```
$ kubectl edit sts mysql
'''
containers:
      - command:
        - bash
        - -ec
        - |
          exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh /tmp/user.sh
```
```
$ cat /tmp/user.sh
#! /bin/bash
mysql -h localhost -P3306 -uroot -p$MARIADB_ROOT_PASSWORD <<EOF
grant all privileges on *.* to 'add'@'%' identified by '${MARIADB_ROOT_PASSWORD}';
flush privileges;
EOF
```
I use root to start my mariadb-galera-cluster, and I found that the dockerfile use mysql user to start mysqld in[ run.sh](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/829fd801c3028a62e4573e09e16e6208dc0c74be/10.5/debian-10/rootfs/opt/bitnami/scripts/mariadb-galera/run.sh#L44)
```
info "** Starting MariaDB **"

set_previous_boot

if am_i_root; then
    exec gosu "$DB_DAEMON_USER" "$EXEC" "${flags[@]}"
else
    exec "$EXEC" "${flags[@]}"
fi
```
but my script is behind of run.sh, why it still to find mysql user?
I am really confused.

**Comment by juan131** [comment]
Hi @lcfang 

You're using the MariaDB Helm chart, right??

You don't need to use a script to grant privileges to certain user on certain database. Instead you can use the `db.user`, `db.password` and `db.name`, and the initialisation logic will create the users for you. See:

- https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#parameters

On the other hand, if you want to run custom scripts, this chart already provides a mechanism to do so you don't need to edit the statefulset. Please refer to the instructions below to do so:

- https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#initialize-a-fresh-instance

**Comment by lcfang** [comment]
@juan131 Hi,thanks for your replay. 

> You're using the MariaDB Galera Helm chart, right??

I really use MariaDB Galera Helm chart

> You don't need to use a script to grant privileges to certain user on certain database

as you see, in my script, I want to have a new user named "add" having privileges to operate all databases but not root, and not for a  certain database, so I think I should exec my script after mysqld ok.

> On the other hand, if you want to run custom scripts, this chart already provides a mechanism to do so you don't need to edit the statefulset. Please refer to the instructions below to do so

my script must run after  mysqld ok. So I think [initalize](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#initialize-a-fresh-instance) is not a good idea for me.
I modify my scritp for waiting `mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD` ok, and run my script in poststart. then mysql can work well with add user.

**Comment by juan131** [comment]
Hi @lcfang 

> my script must run after mysqld ok. So I think initalize is not a good idea for me.

Please use the mechanism provided by chart to include your script. Please note that you custom script will be executed after the database is initialised and root credentials are already configured. Therefore, it should work.
But please, do not modify the default command.

Regarding your script, I noticed that you're adding privileges to that "add" user, without previously creating it... Is that expected?
