### ISSUE TITLE
MariaDB Galera Master > Read Only Slave mode

### ISSUE THREAD

**Issue by Choogster1** [bitnami/bitnami-docker-mariadb-galera#31]
There doesn't appear to be anything mentioned in the documentation listing the environment variables to allow for a Read/Write Master and Read only slave or slaves. Is there such a function in MariaDB Galera, and how do I go about using it? Is there any specific environment variables I can use in my Docker Stack compose file to set up the slaves as read only?

Thanks.

**Comment by carrodher** [comment]
At this moment all the nodes in the MariaDB Galera cluster are in read-write mode and therefore offer high availability for high traffic applications, but there is no way to change this configuration with the existing logic.

We are open to review and merge Pull Requests if it's something you are working on, all the code is publicly available in this repository.
