### ISSUE TITLE
Build for arm64

### ISSUE THREAD

**Issue by dobernoeder** [bitnami/bitnami-docker-mariadb-galera#34]
**Description**

I tried to build this project on a arm64 machine and got stuck with the three packages "ini-file" "mariadb-galera" and "gosu" referenced by libcomponent.sh. I tried to download them in a version for my architecture but it looks like they are only available for amd64 on the bitnami download site.
For example, https://downloads.bitnami.com/files/stacksmith/ini-file-1.3.0-1-linux-arm64-debian-10.tar.gz, was not found. Do you have an arm64 version of these packages on your site? Can you please provide them?

**Steps to reproduce the issue:**

1. Just build the project on arm64 -> It builds successfully

**Describe the results you received:**

After starting the container, an error occurs:
   /opt/bitnami/scripts/libmariadbgalera.sh: line 1411: /opt/bitnami/common/bin/ini-file: cannot execute binary file: Exec format error

**Describe the results you expected:**

I would like to change the architecture in the opt/bitnami/.bitnami_components.json to aarch64 or arm64, so that the download of the prebuild packages would also work for this architecture.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 17:03:40 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Wed Sep 16 17:02:11 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 15
  Running: 10
  Paused: 0
  Stopped: 5
 Images: 134
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 6w6t5fint67da6yh8297lqfno
  Is Manager: true
  ClusterID: p9fauhjvnvngqylguxg2o5no5
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.178.5
  Manager Addresses:
   192.168.178.5:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1022-raspi
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 908.2MiB
 Name: raspserver
 ID: VUYH:E4U5:KF6J:LDRK:77AK:LJ4M:ICQS:O6NZ:MU2C:XKFE:SKWB:VYNC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: dobernoeder
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by FraPazGal** [comment]
Hello @dobernoeder,

Thanks for reaching out! At the moment we are not providing our solutions using ARM architecture, though this is something that it been actively discussed internally and a venue that we want to tackle. Unfortunately, there is no concrete decision yet, so I'm not able to give you an estimate ETA on this.

**Comment by DreamEagle0** [comment]
Can I simply replace the binary files in the three gzip file to arm64? Will it work?

Two repos of them:
[https://github.com/bitnami/ini-file](https://github.com/bitnami/ini-file)
[https://github.com/tianon/gosu](https://github.com/tianon/gosu)

**Comment by rafariossaa** [comment]
If you produce your own arm64 files for :
```
component_unpack "ini-file" "1.3.0-2"
component_unpack "mariadb-galera" "10.5.11-0"
component_unpack "gosu" "1.13.0-0"
```
I guess it should work.
