### ISSUE TITLE
Specify multiple hosts for cluster_address

### ISSUE THREAD

**Issue by NickDubelman** [bitnami/bitnami-docker-mariadb-galera#4]
It seems like you can only pass a single host for `MARIADB_GALERA_CLUSTER_ADDRESS`. This is problematic because the [best practice](https://mariadb.com/kb/en/getting-started-with-mariadb-galera-cluster/#adding-another-node-to-a-cluster) is to set this value to be a comma separated value consisting of all the hosts in the cluster. ("However, it is generally better to list all nodes of the cluster in wsrep_cluster_address, so that any node can join a cluster by connecting to any of the other cluster nodes, even if one or more of the cluster nodes are down.")

The reason you cannot pass a comma separated list of multiple hosts is because `libmysqlgalera.sh` attempts to call `resolveip` on the host, and it seems to assume only one host is passed. If it cannot resolve the IP of the host, it assumes you are in bootstrap mode.

I don't see a straightforward solution to this issue (ie: there is no way to pass multiple hosts as the cluster_address config value when using this image) because this value is passed in as command line arg (and therefore cannot be overridden by a config file)

**Comment by juan131** [comment]
Hi @NickDubelman 

Thanks so much for the feedback and sharing the documentation with the the best practices!

I think we could modify the bash logic available at **libmysqlgalera.sh** so we treat `MARIADB_GALERA_CLUSTER_ADDRESS` as an array. This way, we can properly configure the `wsrep_cluster_address` setting. What do you think?

We can create a task, so we implement this feature when we have bandwidth to do so. You can also contribute creating a PR, we'll be glad to review it.

**Comment by NickDubelman** [comment]
I created a PR, let me know how it looks

**Comment by juan131** [comment]
Thanks @NickDubelman 
Taking a look!
