### ISSUE TITLE
Problem with MariaDB galera after network outage

### ISSUE THREAD

**Issue by Choogster1** [bitnami/bitnami-docker-mariadb-galera#41]
I have a 4 node docker swarm which was affected by a network outage. 

After that, mariadb galera refused to initialize stalling at the 'setting wsrep_sst auth option' command, thus stopping the database from running and caused the dependent application to fail. 

Any idea what caused this?

**Comment by carrodher** [comment]
Can you share with us the logs of the failing initialization? Apart from that, what method are you using to deploy the containers? Any custom environment variable or customization?

This info is useful for us to debug the issue. Thanks

**Comment by Choogster1** [comment]
The log basically shows the initialization getting to exactly 'setting wsrep_sst auth option' and then stopping and not continuing further. It's absolutely normal until that. The containers are deployed using docker stack with a compose file. 

The only extra config I'm using is a fluentd driver for logging from the container and using traefik 2.2.5 as a reverse proxy. 

I'm running one mariadb_galera 5.5 instance as the bootstrap and another as the slave and the data is stored on an NFS drive. 

It works flawlessly with this configuration usually, until the network outage which then caused it to fail.

**Comment by marcosbc** [comment]
@Choogster1 Could you deploy with `BITNAMI_DEBUG=true` to get more information on the specific point where it fails? Please share the full initialization logs as well.

It might be that you will need to deploy with [`MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP`](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L94), but apparently we only documented the usage for the chart (not the Docker image) - More info [here](https://galeracluster.com/2016/11/introducing-the-safe-to-bootstrap-feature-in-galera-cluster/). If you happen to deploy with this option, make sure to backup your data beforehand.

**Comment by Choogster1** [comment]
I can try deploying with bitnami_debug=true. Actually, I have the master galera instance with MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP enabled by default. I shall add the bitnami_debug=true flag in due course and then see what happens with the cluster.
