### ISSUE TITLE
How to run script everytime before mariadb started?

### ISSUE THREAD

**Issue by Eskies** [bitnami/bitnami-docker-mariadb-galera#46]
Hello, Is it possible to run the script every time before MariaDB started? I need to start vpncloud and make sure tun networks are created before MariaDB-Galera starting. I plan to use it across the data center and with a secure VPN.
I plan to customize this image (adding dependency, adding galera.cnf, etc) [https://github.com/bitnami/bitnami-docker-mariadb-galera#customize-this-image](url) following this docs, but I can't use RUN to create VPN interface. Usually, I use ENTRYPOINT, but after reading the source code, I could override the default ENTRYPOINT if I do that.

So is that possible?
Many thanks.

**Comment by andresbono** [comment]
Hi @Eskies, I'd suggest that you modify the existing `entrypoint.sh` and you add there the the commands that you need to execute on every start of the container. Does it make sense?

https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.5/debian-10/rootfs/opt/bitnami/scripts/mariadb-galera/entrypoint.sh

**Comment by Eskies** [comment]
Hi @andresbono , thank you for your response
I thought that first, but would it be safe to modify it? Especially when I update the base image? Considering I will miss entrypoint.sh update because using custom entrypoint. 
If there's a way to do it without touching/modify the base image, it would be great. But if not, guess I'll modify it.

**Comment by andresbono** [comment]
Maybe you can wrap the entrypoint from the base image. Something like this:

```console
cat >custom-entrypoint.sh <<EOF
#!/bin/bash
# Do my actions here
echo "My custom action first..."
exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
EOF

chmod +x custom-entrypoint.sh

docker run --rm -it -v $PWD/custom-entrypoint.sh:/custom-entrypoint.sh --entrypoint /custom-entrypoint.sh bitnami/mariadb-galera
```

That way you will receive updates for the entrypoint script.

**Comment by Eskies** [comment]
Ah, I see. It seems entrypoint will still be run even called from another script. (MariaDB disallow it when I read their script)
I'll try it, and report it if it worked, thank you.
