### ISSUE TITLE
Grant PRIVILEGES not Working

### ISSUE THREAD

**Issue by Hemant0601** [bitnami/bitnami-docker-mariadb-galera#49]
**Description**

**Steps to reproduce the issue:**

1. Deploy a galera cluster on kubenetes
2. Login remotely from ssh
3. Load a large DB
4. Run Grant Commands
5.  It hangs the server

**Describe the results you received:**

```
MariaDB [db_telldus]> GRANT ALL PRIVILEGES ON *.* TO 'db_admin'@'%';
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    39663
Current database: db_telldus

^CCtrl-C -- query killed. Continuing normally.
^CCtrl-C -- query killed. Continuing normally.
ERROR 2013 (HY000): Lost connection to MySQL server during query
MariaDB [db_telldus]> 
```

**Describe the results you expected:**

It should grant permission but instead the privileges remains same

 GRANT USAGE ON *.* TO `db_admin`@`%` IDENTIFIED BY PASSWORD '*AB2730DA5D40D85F2D45CFE68EAEB8D550F6E769' |
| GRANT SELECT, INSERT, UPDATE, CREATE ON `db_telldus`.* TO `db_admin`@`%` 

It should grant proper access

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by carrodher** [comment]
It seems an issue related to the resources assigned to the pods in the k8s cluster. If I am not wrong, everything is up and running without issues, but when a large database is loaded and the command to change the permissions to this large database is executed the server is frozen.

Is the issue solved if you wait more time? I mean, although you are kicked out from the SSH connection the pod (and the container) is still running.
Are you able to see any useful information in the pods' logs or describing the pods? You can use `kubectl logs -f POD_NAME` or `kubectl describe pod POD_NAME`
