### ISSUE TITLE
Feature request: Add option to read passwords from a file

### ISSUE THREAD

**Issue by zachmann** [bitnami/bitnami-docker-mariadb-galera#50]
**Description**

Please consider adding an option for all passwords to pass them via files instead of environment variables.
E.g. add the env var `MARIADB_ROOT_PASSWORD_FILE` as an alternative to `MARIADB_ROOT_PASSWORD`: The root password is then read from the file specified in `MARIADB_ROOT_PASSWORD_FILE`.

**Benefit:**
With these `*_FILE` env vars we can pass passwords in a more secure way and use docker secrets for this purpose.

**Comment by alvneiayu** [comment]
hi @zachmann 

I think that it is something already defined, [here](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/9efe4d194dec05dc9bdc8cb4268c67a00e92f306/10.5/debian-10/rootfs/opt/bitnami/scripts/mariadb-env.sh#L69):

```
for env_var in "${mariadb_env_vars[@]}"; do
            file_env_var="${env_var}_FILE"
            if [[ -n "${!file_env_var:-}" ]]; then
                if [[ -r "${!file_env_var:-}" ]]; then
                    export "${env_var}=$(&lt; "${!file_env_var}")"
                    unset "${file_env_var}"
                else
                    warn "Skipping export of '${env_var}'. '${!file_env_var:-}' is not readable."
                fi
            fi
done
```
This is going to import the password using a file. Is this the feature that you are looking for?

Thanks a lot

Álvaro

**Comment by zachmann** [comment]
Yes that's exactly was I was looking for. Great to here that it's already there (I also was wondering that such options would not be available).

I couldn't find it in the documentation and not in the code. However, I only looked where the password was used. So sorry for the question.

**Comment by alvneiayu** [comment]
hi @zachmann 

No need to apologize. I am happy that I have helped you.

Thanks a lot

Álvaro
