### ISSUE TITLE
How to restart bootstrap node?

### ISSUE THREAD

**Issue by ChristianCiach** [bitnami/bitnami-docker-mariadb-galera#52]
I've read the issue template, but this is a question, so most of the points do not apply. (Maybe you should use the new "discussions"-feature of GitHub?)

Anyway, I don't seem to fully understand the concepts behind this image.

We are deploying a three node galera cluster, using three VMs. No docker-compose, no Kubernetes. Just three VMs with pure Docker.

Following the README of this project, the first node has been deployed with `MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes` and the other two with `MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://[list of all three nodes]`. The resulting cluster works fine, no issues here. Nice!

There is just one issue: Whenever the first node gets restarted (either `docker restart galera` or by just rebooting the VM after a system update), this happens:

```
ERROR ==> It is not safe to bootstrap form this node ('safe_to_bootstrap=0' is set in 'grastate.dat'). If you want to force bootstrap, set the environment variable MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
```

I wonder what the intended solution is. `MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP` is obviously not what I want to do. I don't want to bootstrap a new cluster. I want this node to just re-join the existing cluster, because the other two nodes have quorum.

There must be something I've missed.

Maybe this is your intention: After completely bootstrapping the initial cluster, maybe I should re-deploy the first node with `MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://[list of all three nodes]` and without `MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes`. After this, all three nodes should be equal. Is this the intended way to do this?

**Comment by ChristianCiach** [comment]
I think this is a bug that was introduced by https://github.com/bitnami/bitnami-docker-mariadb-galera/pull/43/files.

Before, this was the code that determines if actual bootstrapping is necessary:

```
    clusterBootstrap="$DB_GALERA_CLUSTER_BOOTSTRAP"
    if is_boolean_yes "$clusterBootstrap"; then
        if is_boolean_yes "$(get_previous_boot)"; then
            clusterBootstrap="no"
        fi
```

So, even if `MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes` is set, it actually does not bootstrap anything because this is not the first boot.

Now it looks like this:
```
    if is_boolean_yes "$DB_GALERA_FORCE_SAFETOBOOTSTRAP"; then
        clusterBootstrap="yes"
    elif is_boolean_yes "$DB_GALERA_CLUSTER_BOOTSTRAP"; then
        clusterBootstrap="yes"
    elif is_boolean_yes "$(get_previous_boot)"; then
        clusterBootstrap="no"
    elif ! is_boolean_yes "$(has_galera_cluster_other_nodes)"; then
        clusterBootstrap="yes"
```

So, if `MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes` is set, it will **always** attempt to bootstrap, disregarding any previous boots.

**Comment by Mauraza** [comment]
Hi @ChristianCiach,

When that error appears you need to force the bootstrap for that node, update `the safe_to_bootstrap=1` in '/bitnami/mariadb/data/grastate.dat'.
We have this documentation for chart https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#all-the-nodes-with-safe_to_bootstrap-0

Could you check this comment before that code?
https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/8963ffd51a32e9f0548b0ed917b01b59e1dace15/10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L87-L108

**Comment by ChristianCiach** [comment]
Hi @Mauraza. I think you have misunderstood my comment. Please also read my comment at https://github.com/bitnami/bitnami-docker-mariadb-galera/pull/43 where I clearly state that I just want to restart the node, not initialize a new cluster bootstrap. 

Forcing `safe_to_bootstrap` on a node that has just been restarted (on a healthy cluster no less) could have really bad consequences. Because the node may not be the one with the latest data anymore, forcing bootstrapping on this node will lead to data loss. Forcing `safe_to_bootstrap` is a cluster recovery mechanism in cases where the whole cluster went down and should never be attempted on a healthy cluster.

Safely restarting the bootstrap node on a healthy cluster worked for yours with this images and has just been very recently been broken by the mentioned PR. I think this is a nearly catastrophic bug.

**Comment by ChristianCiach** [comment]
Forgot to say: Yes, I have read this comment in the code. The comment has not been touched by the PR, but is wrong now. It says that bootstrapping is only done when running "run.sh" for the first time. This has been true for years. With the PR merged, bootstrapping is now done *every time* on the initial bootstrapping node that has `MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes` set.

**Comment by Mauraza** [comment]
Hi @ChristianCiach,

we will review the PR. Thanks for the contributions!!
