### ISSUE TITLE
ist.recv_addr points to public node address  which causes tcp binding issues

### ISSUE THREAD

**Issue by LouBen3010** [bitnami/bitnami-docker-mariadb-galera#55]
**Description**

When defining MARIADB_GALERA_NODE_ADDRESS this is propagated as ist.recv_addr inside the container. But this causes an issue since the container can't bind against a public ip itself is not aware of.

**Steps to reproduce the issue:**

1. Take two separate machines with separate IP addresses (it's not enough to open a fresh docker network)
2. Setup a fresh cluster with only one member (with MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes) on machine a
3. Setup a second node on machine b and define the MARIADB_GALERA_NODE_ADDRESS to its "public" IP address

**Describe the results you received:**

When the second node starts it joins the cluster as expected. Then the replication should start and you see something like this in the logs:
```
app_1  | 2021-07-02  9:51:35 1 [Note] WSREP: IST receiver addr using tcp://<public-ip>:4568
app_1  | 2021-07-02  9:51:35 1 [ERROR] WSREP: State Transfer Request preparation failed: bind: Cannot assign requested address Can't continue, aborting.
```

I assume that when dealing with IP addresses all the examples are working because of the Docker network architecture and its injection into the containers (since most examples are constructed using a single docker-compose.yml). But in my case I need to define the public IPs of the separated nodes which are not visible by the containers itself.

**Describe the results you expected:**

In order to ensure a full encapsulation I would expect the container to bind against tcp://0.0.0.0:4568 so that the port forwarding inside the container is enough to receive the messages.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 18
  Running: 3
  Paused: 0
  Stopped: 15
 Images: 59
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-77-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.775GiB
 Name: mindmotiv-production-2
 ID: WW3N:D2BL:IKR5:PAK5:GUMJ:WN4T:LULH:L623:HWEQ:COLV:WLNU:WVXB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

EDIT:
I also tried to use the host network, bei setting `network_mode: host` in my compose file, but then also the binding fails.

**Comment by alemorcuq** [comment]
I see. Apparently, `ist.recv_addr` gets its default value from `wsrep_node_address`: https://galeracluster.com/library/documentation/galera-parameters.html#ist-recv-addr

Have you tried manually configuring the `ist.recv_addr` setting?

**Comment by LouBen3010** [comment]
I finally got it to work. After a long testing period of IST/SST and IP/Port configuration I got the following extra environment variable in my `docker-compose.yml`:
`- MARIADB_EXTRA_FLAGS=--wsrep_provider_options=ist.recv_addr=<PUBLIC_IP>:4568;ist.recv_bind=0.0.0.0:4568`

This seems to be an easy shot but it was not really clear which addresses will be published to other nodes (which in fact leads to errors if internal docker IPs are sent around). Long story short: The <PUBLIC_IP> will be published to other nodes and the definition of the `ist.recv_bind` overwrites the binding to use 0.0.0.0.

**Comment by LouBen3010** [comment]
Sure that would be enough, but I think when using MariaDB with Galera in container environments there will be always the case that `ist.recv_bind` has to be set to `0.0.0.0:<IST_PORT>` isn't it?
Correct me if I'm wrong, but I think it would be a great way to set it to `0.0.0.0` by default and you can overwrite it using a new environment variable.

**Comment by alemorcuq** [comment]
I will create an internal task to add support for this and analyze if we should set 0.0.0.0 as the default value.
