### ISSUE TITLE
MARIABACKUP_USER and MARIABACKUP_PASSWORD not working ! 

### ISSUE THREAD

**Issue by rabinhod** [bitnami/bitnami-docker-mariadb-galera#58]
Hi
I have two vps and i run container with docker command line 
And my question is: How server 2 can make copy of server one without have passwords !
when i start server 2, it's work fine and it copy all database from server 1 without any error ! i mean replication complete without have correct password of MARIABACKUP_USER and MARIABACKUP_PASSWORD

Server 1

    docker run -d --name mariadb-galera-0 \
      --net host \
      -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
      -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user_a \
      -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password_a \
      -e MARIADB_ROOT_PASSWORD=my_root_password_a \
      -e MARIADB_USER=my_user_a \
      -e MARIADB_PASSWORD=my_password_a \
      -e MARIADB_DATABASE=my_database_a \
      -e MARIADB_REPLICATION_USER=rep_username_a \
      -e MARIADB_REPLICATION_PASSWORD=rep_password_a \
      -v /home/db:/bitnami/mariadb \
      bitnami/mariadb-galera:10.4.20

Server 2

    docker run -d --name mariadb-galera-1 \
      --net host \
      -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
      -e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera:4567,0.0.0.0:4567,SERVER1IP:4567  \
      -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
      -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
      -e MARIADB_ROOT_PASSWORD=my_root_password \
      -e MARIADB_REPLICATION_USER=rep_username \
      -e MARIADB_REPLICATION_PASSWORD=rep_password \
      -v /home/db:/bitnami/mariadb \
      bitnami/mariadb-galera:10.4.20

**Comment by pablogalegoc** [comment]
Hi @rabinhod,

I don't think it is possible since `MARIADB_GALERA_MARIABACKUP_PASSWORD` has no default value and currently it is a required option for the mariabackup cli (there's an open issue asking for this functionality https://jira.mariadb.org/browse/MDEV-19949).

**Comment by rabinhod** [comment]
@pablogalegoc 
But it's work without correct password !
could you test it ?

**Comment by pablogalegoc** [comment]
Hi @rabinhod,

The issue here seems to be that you are setting up two primary nodes. This could be caused by two things in this case:
1. In the first node you are missing `-e MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes \`
2. If the credentials are incorrect
