### ISSUE TITLE
Cluster node reboots can break the cluster

### ISSUE THREAD

**Issue by gwvandesteeg** [bitnami/bitnami-docker-mariadb-galera#67]
**Description**

Similar to #19 when the images are deployed using helm as per the chart from [bitnami chart repo](https://github.com/bitnami/charts) and an update to the chart causes a RollingUpdate to trigger it is ridiculously easy for the database cluster to break if node 0 from the statefulset is not the most recent node.

The documentation provided on trying to recover from a failed cluster as per the documentation [here](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#bootstraping-a-node-other-than-0) is rather unusable.
Since there is already a helm install for the database cluster (especially if using GitOps workflows such as [Flux](https://fluxcd.io/) ), any attempt to recover the nodes will run into the problems of:

- Which node is the one with the most recent sequence number, you would either need to discover this with attaching another workload to the underlying storage volume being used, deal with a crashlooping node and try and do things between crashes and restarts, or use an ephemeral container (not yet supported it seems).
- The podManagementPolicy on an existing StatefulSet cannot be changed post deployment to Parallel, which makes all attemps to try and utilise this approach from the doc above pointless.
- If you have no nodes which are safe to bootstrap any attempt to bootstrap one of them will run into the issue that the
  the `wsrep_cluster_address` setting will be referencing the mariadb-galera service which will be referencing the endpoints of the currently running nodes, which needs to be managed safely in a recovery operation of the cluster.
- If the wrong node gets bootstrapped (somehow) you'll end up with split brains and distinct clusters which are a right pain to recover from.

**Steps to reproduce the issue:**

1. Deploy a three node cluster using the helm chart
2. Store some data in a particular node (you can try iterating over all with this process to see how each upgrade behaves).
3. Change the configuration and upgrade the helm chart deployment, or reschedule a pod onto a new worker node.
4. Enjoy the broken bits and try to get the cluster restored.

**Describe the results you received:**

Broken cluster, ended up with split brain across all three nodes, any attempt to salvage made the problems worse.  Eventually just tore down the entire cluster, recreated it and restored from backups.  All to get a single configuration change deployed, `log_bin_trust_function_creators=on`.

**Describe the results you expected:**

No matter which node is the active node, when a rolling update or workload rescheduling occurs the database recovers gracefully and rejoins the cluster no matter where it was now scheduled.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Tested with both Helm chart versions: 5.9.0, 5.14.0 on AWS EKS 1.20

**Note**

Don't want to think what is going to be involved in doing an upgrade of the EKS cluster to a new version if a simple reboot/reschedule of a node can cause the entire thing to fail.

**Comment by gwvandesteeg** [comment]
Also referencing: https://github.com/bitnami/charts/issues/2260

And in particular this post: https://github.com/bitnami/charts/issues/2260#issuecomment-715473632

**Comment by rafariossaa** [comment]
I think this is the problem with galera when it is run in k8s, when stopped you don't know which is the right node to start from again, and unless some kind of operator is implemented each node independently won't be able to resolve the situation.
Maybe, as workaround of this situation, you can scale down the cluster to one node previous to the upgrade, and them scale it up to the number of desired nodes.

**Comment by gwvandesteeg** [comment]
The problem with the scale down as well is that you don't know when the scaling happens as to which node is the one with the most recent write/sequence number.  If you're lucky it's the node that remains after the scale down.

**Comment by rafariossaa** [comment]
Sorry, I think I didn't explain my self very well.
I meant, to scale down to just one node, so after the upgrade, when you scale up again the new nodes will sync from that one without issues.
