### ISSUE TITLE
I cannot create clusters in "docker service create"

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [bitnami/bitnami-docker-mariadb-galera#71]
source（https://github.com/bitnami/bitnami-docker-mariadb-galera）:
![image](https://user-images.githubusercontent.com/39817817/144806598-d9e28abd-278b-44ba-a865-a349483a5268.png)

1.execution CMD instruction

```console
docker service create -p 3306:3306   -e MARIADB_GALERA_CLUSTER_NAME=my_galera   -e MARIADB_GALERA_MARIABACKUP_USER=backup   -e MARIADB_GALERA_MARIABACKUP_PASSWORD=backup   -e MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes   -e MARIADB_ROOT_PASSWORD=root   -e MARIADB_REPLICATION_USER=replication   -e MARIADB_REPLICATION_PASSWORD=replication   --name mariadb-galera-0   bitnami/mariadb-galera:latest
```

2.error message
![Snipaste_2021-12-06_15-31-44](https://user-images.githubusercontent.com/39817817/144806470-e0166704-5aa9-4289-b9bb-e56e7bcbfdd5.png)

**Comment by juan131** [comment]
Hi @Conmi-WhiteJoker 

I'm not very familiar with the `docker service create` command, but it looks like you're missing the `--name` and `--hostname` parameters in your command so you define a container name and hostname, see:

- https://docs.docker.com/engine/reference/commandline/service_create/

That should help you preventing the `Name or service not known` error.
