### ISSUE TITLE
Crashing cluster

### ISSUE THREAD

**Issue by universenl** [bitnami/bitnami-docker-mariadb-galera#72]
Good day,

**Description**
We are running Mariadb Galera on our Kubernetes cluster thats on Azure AKS, we running this also in production with alot of data inside it. Last couple of weeks we had some issues running a new Galera cluster on a new AKS cluster.

Eventually we fixed this (we using manually deployment, so no helm) and now we find a new issue that also exists on our OTAP an PROD cluster. 

**Details**
Image: bitnami/mariadb-galera

**Issue**
Randomly deleting pods seems to be able to bring down all other pods and stopping the Galera cluster when we need to bootstrap it again.

This issue seems to be very random, sometimes it happends after a new deployment when we remove the first pod. But many times we need to remove like 4-5 pods before it happends again.

Can someone support on this ?

**Comment by mattiashem** [comment]
https://github.com/bitnami/charts/issues/8331

**Comment by universenl** [comment]
Thanks for the information, can you give me some more information about this release ? 
Because i cannot find this one anywhere.

**Comment by juan131** [comment]
Let's continue discussion at bitnami/charts#8331
