### ISSUE TITLE
Failed to create mariadb-galera cluster in k3s cluster

### ISSUE THREAD

**Issue by Cryingmouse** [bitnami/bitnami-docker-mariadb-galera#73]
**Description**
In my k3s environment, I tried to fresh install mariadb galera cluster with the image `mariadb-galera-6.0.10.tgz` which is downloaded through the command `helm pull bitnami/mariadb-galera`. In the most cases, the 2nd mariadb pod can not start. I tried several time , sometimes, it can also create three mariadb galera clusters for each pod.

**Steps to reproduce the issue:**
1. Pull mariadb galera image
`helm pull bitnami/mariadb-galera`
2. Define the customized values.yaml
```
image:
  debug: true
rootUser:
  user: root
  password: "NAS_PASS"
  forcePassword: true
db:
  user: "dsm"
  password: "NAS_PASS"
  name: DSM
  forcePassword: true
galera:
  bootstrap:
    bootstrapFromNode: "0"
  mariabackup:
    user: mariabackup
    password: "NAS_PASS"
    forcePassword: true
```
3. Generate the yaml file with the command
`helm template mariadb-galera ./mariadb-galera-6.0.10.tgz  --output-dir ./output/ -f values.yaml`
4. Deploy the mariadb galera cluster with the command
`kubectl apply -R -f ./output/mariadb-galera/templates/`
5. Waiting for the mariadb galera cluster startup, but it failed in the 2nd node.
```
[root@ceph1 jay]# kubectl get po -o wide
NAME               READY   STATUS             RESTARTS        AGE     IP           NODE    NOMINATED NODE   READINESS GATES
mariadb-galera-0   1/1     Running            0               9m51s   10.42.0.15   ceph1   <none>           <none>
mariadb-galera-1   0/1     CrashLoopBackOff   5 (2m23s ago)   9m4s    10.42.2.26   ceph3   <none>           <none>
```
**Describe the results you received:**
Failed to start the 2nd pod. 

**Describe the results you expected:**
It is expected that mariadb galera cluster set up successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

Actually there are several cases I met. In most of the cases, the 2nd pod can not start successfully. Sometimes, it created three galera clusters with one member per pod. I also met few cases that can create the expected cluster successfully. It is so weird.  

**Version**

- My k3s environment is as follow:
```
[root@ceph1 ~]# k3s --version
k3s version v1.22.2+k3s2 (3f5774b4)
go version go1.16.8
```
```
[root@ceph1 jay]# kubectl get node
NAME    STATUS   ROLES                  AGE    VERSION
ceph1   Ready    control-plane,master   6d4h   v1.22.2+k3s2
ceph2   Ready    control-plane,master   6d4h   v1.22.2+k3s2
ceph3   Ready    control-plane,master   6d4h   v1.22.2+k3s2
```
The logs from 1st pod:
[node1.txt](https://github.com/bitnami/bitnami-docker-mariadb-galera/files/7777960/node1.txt)

The logs from 2nd pod
[node2.txt](https://github.com/bitnami/bitnami-docker-mariadb-galera/files/7777961/node2.txt)

**Comment by floek** [comment]
Same problem here with latest Bitnami helm chart 6.1.0

**Comment by Mauraza** [comment]
Hi @Cryingmouse  and @floek, 

Did you try to restart coredns?
```bash
kubectl -n kube-system rollout restart deployment coredns
```

**Comment by floek** [comment]
Hi @Mauraza ,
no but It worked with helm chart version 5.6.2. See also https://github.com/bitnami/charts/issues/8277

Best,

Floek

**Comment by Mauraza** [comment]
Hi @floek,
 
>  no but It worked with helm chart version 5.6.2. See also [bitnami/charts#8277](https://github.com/bitnami/charts/issues/8277)

To avoid duplicity issues we continue with the issue you mentioned.

**Comment by Cryingmouse** [comment]
> Hi @Cryingmouse and @floek,
> 
> Did you try to restart coredns?
> 
> ```shell
> kubectl -n kube-system rollout restart deployment coredns
> ```
```
[root@node-1 dns]# kubectl get po -n kube-system -l k8s-app=kube-dns
NAME                      READY   STATUS    RESTARTS   AGE
coredns-7cb98cfdf-x9wsk   1/1     Running   0          5h31m
[root@node-1 dns]# kubectl get svc
NAME                      TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
kubernetes                ClusterIP   10.43.0.1     <none>        443/TCP                      44h
mariadb-galera            ClusterIP   10.43.110.9   <none>        3306/TCP                     17h
mariadb-galera-headless   ClusterIP   None          <none>        4567/TCP,4568/TCP,4444/TCP   17h
[root@node-1 dns]# kubectl get pod
NAME               READY   STATUS             RESTARTS          AGE
dnsutils           1/1     Running            0                 2m25s
mariadb-galera-0   1/1     Running            0                 17h
mariadb-galera-1   0/1     CrashLoopBackOff   190 (4m35s ago)   17h
[root@node-1 dns]# kubectl exec -it dnsutils -- nslookup mariadb-galera-headless
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   mariadb-galera-headless.default.svc.cluster.local
Address: 10.42.2.33
Name:   mariadb-galera-headless.default.svc.cluster.local
Address: 10.42.1.32
```

**Comment by Mauraza** [comment]
Hi @Cryingmouse,

please continue the discussion in the other thread.

**Comment by Cryingmouse** [comment]
Sure, I will keep an eye on bitnami/charts#8277
