### ISSUE TITLE
[K8S] Is there now a YML profile for deploying mariadb-galera based on helm?

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [bitnami/bitnami-docker-mariadb-galera#74]
I found bitnami's Mariadb-Galera here (https://artifacthub.io/packages/helm/bitnami/mariadb-galera) , but I failed to find the complete configuration file of helm similar to docker-comemage. yml. I would like to learn how to configure Mariadb-Galera with helm, could you please ask where I can get this template?

**Comment by carrodher** [comment]
It can be found at the [Bitnami Helm Charts repository](https://github.com/bitnami/charts), specifically, MariaDB Galera can be found at https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera

**Comment by Conmi-WhiteJoker** [comment]
> It can be found at the [Bitnami Helm Charts repository](https://github.com/bitnami/charts), specifically, MariaDB Galera can be found at https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera

Thank you, carrodher.👍

**Comment by Conmi-WhiteJoker** [comment]
> It can be found at the [Bitnami Helm Charts repository](https://github.com/bitnami/charts), specifically, MariaDB Galera can be found at https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera

It seems that this file cannot be run directly in "helm install my-release bitnami/mariadb-galera -f value.yaml" mode. Is there a configuration file that can run galera mode directly?
(https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/values.yaml)

**Comment by carrodher** [comment]
Please note the bitnami/mariadb-galera Helm chart can be deployed with default parameters by running:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install my-release bitnami/mariadb-galera
```

If you want to provide custom values you should create your own _values.yaml_ or use the one present in the repo (the ones in the link from your previous comment), this _values.yaml_ file should be present in the same path used after the `-f` flag. Please visit the [official Helm documentation](https://helm.sh/docs/) for instructions about how to deploy Helm charts or the [bitnami/mariadb-galera README](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#mariadb-galera) for instructions about this specific Helm chart.

**Comment by dravenk** [comment]
In my case. I set the first node to 
```
#vi /bitnami/mariadb/mariadb/data/grastate.dat 
safe_to_bootstrap: 1
```
For other nodes, set this parameter to 0
```
safe_to_bootstrap: 0
```
