### ISSUE TITLE
Galera doesn't work with bridged networks, nodes can not connect to other's IST recieve address

### ISSUE THREAD

**Issue by wxiaoguang** [bitnami/bitnami-docker-mariadb-galera#77]
### Name and Version

10.6.7

### What steps will reproduce the bug?

Galera doesn't work with bridged networks, nodes can not connect to other's IST recieve addr.

#### Env

My host's network is 10.0.0.0/8  (eg: host IP: 10.0.100.5)
My container's network is 172.16.0.0/12

#### The bug

Even if I set `wsrep_node_incoming_address` and `wsrep_sst_receive_address` to host's IP 10.0.100.5, each node still try to connect other's IST receiver at 172.18.0.x (which is reported by the Galera engine internally), which it not connectable, and result in timeout and failure.

If I set MARIADB_GALERA_NODE_ADDRESS to 10.0.100.5, then Galera won't start because it tries to bind on 10.0.100.5, which is not available in a bridged network.

#### Bypass

Now, a possible way to bypass the problem is to set `network_mode: host` and `MARIADB_GALERA_NODE_ADDRESS=host-ip`, then the Galera cluster can use the host network to work correctly.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but I not very sure of your issue. 
  For example, if you use the[ default compose file](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.5/debian-10/docker-compose.yml), you should be able to access the galera database by using `localhost:3306`.
  A bridged network will have its own addresses, and usually, from that addressing you will be able to reach other addresses through the gateway, but not the other way around. Maybe this [link](https://docs.docker.com/network/bridge/#title) can bring more details.

**Comment by wxiaoguang** [comment]
Thank you for your quick response.

I think this issue is the same as 

* https://github.com/bitnami/bitnami-docker-mariadb-galera/issues/55

**Comment by wxiaoguang** [comment]
ps: if users follows the README document, they won't succeed to build a Galera cluster. The nodes can not communicate  with each other using IST protocol by default, when the nodes are on different hosts.

Users should either:
* set `--wsrep_provider_options=ist.recv_addr=<PUBLIC_IP>:4568;ist.recv_bind=0.0.0.0:4568 --wsrep_node_incoming_address=<PUBLIC_IP> --wsrep_sst_receive_address=<PUBLIC_IP>`, 
* or use the method in this issue: set `network_mode: host` and `MARIADB_GALERA_NODE_ADDRESS=host-ip`

**Comment by rafariossaa** [comment]
Hi,
  I am not sure if you got your scenario right. 
  You have several hosts (VMs / baremetal) and in each you are running a galera node in docker. Am I right ?

**Comment by wxiaoguang** [comment]
> Hi, I am not sure if you got your scenario right. You have several hosts (VMs / baremetal) and in each you are running a galera node in docker. Am I right ?

Yes.

Example:

* Host1: 10.0.100.3   Docker: 172.18.1.11 , mariadb-galera-node-a
* Host1: 10.0.100.4   Docker: 172.19.2.22 , mariadb-galera-node-b
* Host1: 10.0.100.5   Docker: 172.20.3.33 , mariadb-galera-node-c

Pure docker, no swarm, no k8s.

**Comment by javsalgar** [comment]
Hi,

So, from what I see, there is currently a way to set this by using the environment extra flags, right?

**Comment by wxiaoguang** [comment]
I think so, it's a bypass method. Either use environment extra flags, or use host network (they are mentioned in the previous comment)

**Comment by javsalgar** [comment]
Hi,

Good to know that. It is not clear to me if the installation you are using is that common that it requires us to perform special changes in the container. We already test the installation in docker and in major Kubernetes distributions. Let's see if more people from the community consider this use case important for the container or with the workaround is enough.

**Comment by wxiaoguang** [comment]
`common or not` it depends how people think about it ....

This problem only occurs for pure docker users without k8s/overlay network (in fact it always occurs for pure docker users), and the author of issue #55 and I all meet this problem.

I think there could be some possible solutions:

Solution 1: introduce a new environment variable like `MARIADB_GALERA_NODE_PUBLIC_IP`, if it is set, then set all these `recv_addr` / `wsrep_node_incoming_address` / `wsrep_sst_receive_address` and maybe more.

Solution 2: update the document to describe the problem and teach docker users how to set public IP correctly or use the docker host network.

Of course, solution 1 is much more easy and friendly for end users.

**Comment by rafariossaa** [comment]
Hi,
  As @javsalgar mentioned, let's see if more people from the community consider this use case important. 
  In any case, maybe you want to consider to send a PR with the approach you like most. We will be glad to review and merge it.

**Comment by wxiaoguang** [comment]
I proposed a PR to update the document.

* https://github.com/bitnami/bitnami-docker-mariadb-galera/pull/78

**Comment by rafariossaa** [comment]
Thanks for the PR
