### ISSUE TITLE
Encryption variables in custom .cnf causing container crash

### ISSUE THREAD

**Issue by EdsonBittencourt** [bitnami/bitnami-docker-mariadb-galera#80]
### Name and Version

bitnami/mariadb-galera:10.7

### What steps will reproduce the bug?

Hello everyone,

We are trying to bootstrap a cluster with a customized .cnf because we need encryption. The custom .cnf variables are:

```
[mysqld]
plugin-load-add=file_key_management.so
innodb_encrypt_tables=1
innodb_encrypt_log=1
innodb-encryption-threads=4
aria_encrypt_tables=1
encrypt-tmp-disk-tables=1
file_key_management_filename="/path/to/key"
```

### What is the expected behavior?

The expected behavior is the database running healthy and with the variables above customized, as it works perfectly if I don't change it.

### What do you see instead?

When I run with all the variables above customized, the container crashes and the container logs just show me this:

```
mariadb 21:29:53.13 INFO  ==> ** Starting MariaDB setup **
mariadb 21:29:53.35 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 21:29:54.43 INFO  ==> Initializing mariadb database
mariadb 21:29:54.68 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 21:29:54.74 INFO  ==> Setting user option
mariadb 21:29:54.93 INFO  ==> Setting wsrep_node_name option
mariadb 21:29:55.11 INFO  ==> Setting wsrep_node_address option
mariadb 21:29:55.21 INFO  ==> Setting wsrep_cluster_name option
mariadb 21:29:55.32 INFO  ==> Setting wsrep_sst_auth option
```

But, doing some troubleshooting I noticed that the variables that are causing the crash are innodb_encrypt_tables, innodb_encrypt_log and aria_encrypt_tables. If I comment just these variables the cluster start and the container keeps running. 

If I leave any of these variables uncommented the issue happens. The container only keeps running if I comment all three.

May someone experience something like that?

**Comment by carrodher** [comment]
In order to increase the log level in the container, can you please add the `image.debug=true` parameter? In that way, more info will be shown in the container output.

**Comment by EdsonBittencourt** [comment]
Hello @carrodher! Thank you for the answer.

I've enable the debug with '-e BITNAMI_DEBUG=true' and the log returns me that the problem could be conflicting information in an external .cnf file, but my external cnf file contains just the encryption variables. 

`mariadb 12:55:55.78 Welcome to the Bitnami mariadb-galera container
mariadb 12:55:55.80 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
mariadb 12:55:55.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
mariadb 12:55:55.84
mariadb 12:55:55.86 INFO  ==> ** Starting MariaDB setup **
mariadb 12:55:56.08 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 12:55:56.12 DEBUG ==> Set Galera cluster address to gcomm://
mariadb 12:55:57.20 INFO  ==> Initializing mariadb database
mariadb 12:55:57.23 DEBUG ==> Ensuring expected directories/files exist
mariadb 12:55:57.50 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 12:55:57.55 DEBUG ==> Injecting custom configuration from my_custom.conf
mariadb 12:55:57.58 INFO  ==> Setting user option
mariadb 12:55:57.60 DEBUG ==> Setting user to 'user_maria' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 12:55:57.77 INFO  ==> Setting wsrep_node_name option
mariadb 12:55:57.79 DEBUG ==> Setting wsrep_node_name to '2962a0472326' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 12:55:57.97 INFO  ==> Setting wsrep_node_address option
mariadb 12:55:57.99 DEBUG ==> Setting wsrep_node_address to '172.17.0.2' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 12:55:58.09 INFO  ==> Setting wsrep_cluster_name option
mariadb 12:55:58.11 DEBUG ==> Setting wsrep_cluster_name to 'galera-cluster' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 12:55:58.22 DEBUG ==> Set Galera cluster address to gcomm://
mariadb 12:55:58.24 INFO  ==> Setting wsrep_sst_auth option
mariadb 12:55:58.26 DEBUG ==> Setting wsrep_sst_auth to 'user_bkp:123' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 12:55:58.37 INFO  ==> Injecting custom configuration 'my_custom.cnf'
mariadb 12:55:58.40 DEBUG ==> Cleaning data directory to ensure successfully initialization
Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...

Installation of system tables failed!  Examine the logs in
/bitnami/mariadb/data for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /opt/bitnami/mariadb/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /opt/bitnami/mariadb/sbin/mariadbd --skip-grant-tables --general-log &

and use the command line tool /opt/bitnami/mariadb/bin/mariadb
to connect to the mysql database and look at the grant tables:

    shell> /opt/bitnami/mariadb/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /bitnami/mariadb/data that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at https://mariadb.org/jira`

**Comment by m-guest** [comment]
We can confirm this behavior and receiving same error logs.

In addition to the settings mentioned in this issue, the following configuration settings are causing it too:
```
encrypt_binlog=ON
encrypt_tmp_files=ON
```

Versions tested and affected by this issue:
`10.6.7-debian-10-r44`
`10.7`

Last versions tested and **NOT** affected by this issue:
`10.6.4-debian-10-r44`
`10.6.5-debian-10-r68`

**Comment by EdsonBittencourt** [comment]
> We can confirm this behavior and receiving same error logs.
> 
> In addition to the settings mentioned in this issue, the following configuration settings are causing it too:
> 
> ```
> encrypt_binlog=ON
> encrypt_tmp_files=ON
> ```
> 
> Versions tested and affected by this issue: `10.6.7-debian-10-r44` `10.7`
> 
> Last versions tested and **NOT** affected by this issue: `10.6.4-debian-10-r44` `10.6.5-debian-10-r68`

Even with these versions I can't make it work. May you share your custom .cnf file, please?

**Comment by m-guest** [comment]
@EdsonBittencourt Tested with helm chart `bitnami/mariadb-galera` version `6.0.0`. Most of the config is defaults from chart [values.yaml](https://github.com/bitnami/charts/blob/fe1a645434795c0838904e2b8cf0041a2ed904e0/bitnami/mariadb-galera/values.yaml#L347-L471), or very similar. The relevant part for encryption at rest is taken from defaults, just not commented.

```
[mariadb]
plugin_load_add=auth_pam

## Data-at-Rest Encryption
## Use extraVolumes and extraVolumeMounts to mount /encryption filesystem
plugin_load_add=file_key_management
file_key_management_filename=/encryption/keyfile
file_key_management_encryption_algorithm=AES_CTR
encrypt_binlog=ON
encrypt_tmp_files=ON

## InnoDB/XtraDB Encryption
innodb_encrypt_tables=ON
innodb_encrypt_temporary_tables=ON
innodb_encrypt_log=ON
innodb_encryption_threads=4
innodb_encryption_rotate_key_age=1

## Aria Encryption
aria_encrypt_tables=ON
encrypt_tmp_disk_tables=ON
```

**Comment by dgomezleon** [comment]
Hi @EdsonBittencourt ,

Did you mount the `file_key_management_filename` file? I was able to make it work by creating and mounting this file.

I hope it helps

**Comment by EdsonBittencourt** [comment]
> Hi @EdsonBittencourt ,
> 
> Did you mount the `file_key_management_filename` file? I was able to make it work by creating and mounting this file.
> 
> I hope it helps

@m-guest ,

Thank you.

@dgomezleon,

You're right. In 10.6.5 mount the the file solved my issue. Thank you so much.
But according my tests, the latest versions are really crashing with some variables.
