### ISSUE TITLE
Wrong environment variable MARIADB_ENABLE_SSL in README.md

### ISSUE THREAD

**Issue by schube** [bitnami/bitnami-docker-mariadb-galera#81]
### Name and Version

bitnami-docker-mariadb-galera

### What steps will reproduce the bug?

MARIADB_ENABLE_SSL is wrong, actually it is MARIADB_ENABLE_TLS

### What do you see instead?

the wrong, not working, environment variable

**Comment by javsalgar** [comment]
Hi,

Thanks for spotting the issue! Would you like to submit a PR changing the README.md file?
