### ISSUE TITLE
Galera mariadb pod restarting after Setting wsrep_sst_auth option as per logs

### ISSUE THREAD

**Issue by ChetanSheelwant** [bitnami/bitnami-docker-mariadb-galera#82]
### Name and Version

bitnami/mariadb-galera:latest

### What steps will reproduce the bug?

1. K8s version1.22.8 on Oracle Linux 8.4
2. Installed helm version 3.8.2
3. Installing galera cluster using the cli 'helm install my-release --set rootUser.forcePassword=true --set rootUser.password=secretpassword --set db.user=app_database --set db.name=galera_mariadb --set global.storageClass=csi-infoscale-mirror-sc --set image.tag=latest --set service.type=NodePort --set service.nodePort=30001 --set galera.mariabackup.forcePassword=true --set galera.mariabackup.password=secretpassword --set persistence.size=5Gi --set livenessProbe.enabled=true --set livenessProbe.initialDelaySeconds=300 --set readinessProbe.enabled=true --set readinessProbe.initialDelaySeconds=300 --set startupProbe.enabled=true --set startupProbe.initialDelaySeconds=300  bitnami/mariadb-galera'
4. The pvc is bound to the pod correctly in RWO mode
5. But the my-release-mariadb-galera-0 pod restart after around 120 sec, 
6. Log attaching : 
[galera_mariadb_deploy_2022-04-24_failing_k8s-1-22-8.log](https://github.com/bitnami/bitnami-docker-mariadb-galera/files/8549211/galera_mariadb_deploy_2022-04-24_failing_k8s-1-22-8.log)

7. Earlier the same option for deploying galera mariadb cluster used to work perfectly fine.

### What is the expected behavior?

Expected that the galera maria db pod to be up and running instead of going in crash-loop-back state

[root@vm01p1 ~]# kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
my-release-mariadb-galera-0   1/1     Running   0          11m
my-release-mariadb-galera-1   1/1     Running   0          6m32s
my-release-mariadb-galera-2   0/1     Running   0          79s
[root@vm01p1 ~]#

### What do you see instead?

[root@punr740xd-32 ~]# kubectl get pod
NAME                          READY   STATUS             RESTARTS      AGE
my-release-mariadb-galera-0   0/1     CrashLoopBackOff   4 (43s ago)   10m
[root@punr740xd-32 ~]#

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami charts. Could  you redeploy the chart with `image.debug=true`? This should provide more insight on the error.

**Comment by ChetanSheelwant** [comment]
Hi,

Following is the log after trying to deploy with image.debug=true

[root@punr740xd-32 ~]# kubectl logs -f --tail=100 my-release-mariadb-galera-0
mariadb 08:42:41.19
mariadb 08:42:41.19 Welcome to the Bitnami mariadb-galera container
mariadb 08:42:41.20 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
mariadb 08:42:41.20 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
mariadb 08:42:41.20
mariadb 08:42:41.21 INFO  ==> ** Starting MariaDB setup **
mariadb 08:42:41.25 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 08:43:29.46 DEBUG ==> Set Galera cluster address to gcomm://
mariadb 08:43:29.47 INFO  ==> Initializing mariadb database
mariadb 08:43:29.48 DEBUG ==> Ensuring expected directories/files exist
mariadb 08:43:29.56 INFO  ==> Found mounted configuration directory
mariadb 08:43:29.58 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 08:43:29.59 INFO  ==> Setting user option
mariadb 08:43:29.60 DEBUG ==> Setting user to 'app_database' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 08:43:29.61 INFO  ==> Setting slow_query_log option
mariadb 08:43:29.61 DEBUG ==> Setting slow_query_log to '0' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 08:43:29.62 INFO  ==> Setting long_query_time option
mariadb 08:43:29.62 DEBUG ==> Setting long_query_time to '10.0' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 08:43:29.64 INFO  ==> Setting wsrep_node_name option
mariadb 08:43:29.64 DEBUG ==> Setting wsrep_node_name to 'my-release-mariadb-galera-0' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 08:43:29.67 INFO  ==> Setting wsrep_node_address option
mariadb 08:43:29.67 DEBUG ==> Setting wsrep_node_address to '172.16.239.70' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 08:43:53.80 DEBUG ==> Set Galera cluster address to gcomm://
mariadb 08:43:53.81 INFO  ==> Setting wsrep_sst_auth option
mariadb 08:43:53.81 DEBUG ==> Setting wsrep_sst_auth to 'mariabackup:secretpassword' in mariadb configuration file /opt/bitnami/mariadb/conf/my.cnf
mariadb 08:44:17.93 DEBUG ==> Cleaning data directory to ensure successfully initialization
Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...

Installation of system tables failed!  Examine the logs in
/bitnami/mariadb/data for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /opt/bitnami/mariadb/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /opt/bitnami/mariadb/sbin/mariadbd --skip-grant-tables --general-log &

and use the command line tool /opt/bitnami/mariadb/bin/mariadb
to connect to the mysql database and look at the grant tables:

    shell> /opt/bitnami/mariadb/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /bitnami/mariadb/data that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at https://mariadb.org/jira

[root@punr740xd-32 ~]#

**Comment by fmulero** [comment]
Hi @ChetanSheelwant the issue was reproduced and we are investigating the cause. Have you noticed this issue in previous versions?

We will keep you posted on with any news

**Comment by ChetanSheelwant** [comment]
Hi Fran,
Till some days back the the same used to work till around Feb-22, where the OS was same i.e. OEL 8.4, but the change that we have done is moved the Kubernetes version from 1.20.11 to 1.22.5. 
And the regarding the Galera MariaDB image, we always use the latest (image.tag=latest), so not sure about the exact version of the image where it actually worked

**Comment by fmulero** [comment]
Hi @ChetanSheelwant 

The `bitnami/mariadb-galera` chart is using by default mariadb `10.6`. You are setting `image.tag=latest` so at some point you started using mariadb `10.7` instead of` 10.6`. We warn always about the use of rolling tags due to this reason, more information [here](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/).

My recommendation, if you are working in a development environment and you don't need version `10.7`, set `image.tag=10.6` this configuration will use latest release for version `10.6`.

If you need version `10.7` you need to change also the value `mariadbConfiguration` (please have a look to [Incompatible Changes Between 10.6 and 10.7](https://mariadb.com/kb/en/upgrading-from-mariadb-106-to-mariadb-107/#incompatible-changes-between-106-and-107)):
```yaml
mariadbConfiguration: |-
  [client]
  port=3306
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  plugin_dir=/opt/bitnami/mariadb/plugin

  [mysqld]
  default_storage_engine=InnoDB
  basedir=/opt/bitnami/mariadb
  datadir=/bitnami/mariadb/data
  plugin_dir=/opt/bitnami/mariadb/plugin
  tmpdir=/opt/bitnami/mariadb/tmp
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid
  bind_address=0.0.0.0

  ## Character set
  ##
  collation_server=utf8_unicode_ci
  init_connect='SET NAMES utf8'
  character_set_server=utf8

  ## MyISAM
  ##
  key_buffer_size=32M
  myisam_recover_options=FORCE,BACKUP

  ## Safety
  ##
  skip_host_cache
  skip_name_resolve
  max_allowed_packet=16M
  max_connect_errors=1000000
  sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
  sysdate_is_now=1

  ## Binary Logging
  ##
  log_bin=mysql-bin
  expire_logs_days=14
  # Disabling for performance per http://severalnines.com/blog/9-tips-going-production-galera-cluster-mysql
  sync_binlog=0
  # Required for Galera
  binlog_format=row

  ## Caches and Limits
  ##
  tmp_table_size=32M
  max_heap_table_size=32M
  # Re-enabling as now works with Maria 10.1.2
  query_cache_type=1
  query_cache_limit=4M
  query_cache_size=256M
  max_connections=500
  thread_cache_size=50
  open_files_limit=65535
  table_definition_cache=4096
  table_open_cache=4096

  ## InnoDB
  ##
  innodb=FORCE
  innodb_strict_mode=1
  # Mandatory per https://github.com/codership/documentation/issues/25
  innodb_autoinc_lock_mode=2
  # Per https://www.percona.com/blog/2006/08/04/innodb-double-write/
  innodb_doublewrite=1
  innodb_flush_method=O_DIRECT
  innodb_log_files_in_group=2
  innodb_log_file_size=128M
  innodb_flush_log_at_trx_commit=1
  innodb_file_per_table=1
  # 80% Memory is default reco.
  # Need to re-evaluate when DB size grows
  innodb_buffer_pool_size=2G
  innodb_file_format=Barracuda

  ## Logging
  ##
  log_error=/opt/bitnami/mariadb/logs/mysqld.log
  slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
  log_queries_not_using_indexes=1
  slow_query_log=1

  ## SSL
  ## Use extraVolumes and extraVolumeMounts to mount /certs filesystem
  # ssl_ca=/certs/ca.pem
  # ssl_cert=/certs/server-cert.pem
  # ssl_key=/certs/server-key.pem

  [galera]
  wsrep_on=ON
  wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
  wsrep_sst_method=mariabackup
  wsrep_slave_threads=4
  wsrep_cluster_address=gcomm://
  wsrep_cluster_name=galera
  wsrep_sst_auth="root:"
  # Enabled for performance per https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
  innodb_flush_log_at_trx_commit=2
  # MYISAM REPLICATION SUPPORT #
  # CHANGED IN 10.7 https://mariadb.com/kb/en/upgrading-from-mariadb-106-to-mariadb-107/
  #wsrep_replicate_myisam=ON  
  wsrep_mode=REPLICATE_MYISAM


  [mariadb]
  plugin_load_add=auth_pam

  ## Data-at-Rest Encryption
  ## Use extraVolumes and extraVolumeMounts to mount /encryption filesystem
  # plugin_load_add=file_key_management
  # file_key_management_filename=/encryption/keyfile.enc
  # file_key_management_filekey=FILE:/encryption/keyfile.key
  # file_key_management_encryption_algorithm=AES_CTR
  # encrypt_binlog=ON
  # encrypt_tmp_files=ON

  ## InnoDB/XtraDB Encryption
  # innodb_encrypt_tables=ON
  # innodb_encrypt_temporary_tables=ON
  # innodb_encrypt_log=ON
  # innodb_encryption_threads=4
  # innodb_encryption_rotate_key_age=1

  ## Aria Encryption
  # aria_encrypt_tables=ON
  # encrypt_tmp_disk_tables=ON
```

NOTE: This `10.7` configuration is not fully tested nor officially supported at the moment for this chart

**Comment by ChetanSheelwant** [comment]
Hi Fran,
As suggested switched back to 10.6 and the deployment worked fine. Thanks for all the help.
