### ISSUE TITLE
Enable SSL on port 3306

### ISSUE THREAD

**Issue by fabry00** [bitnami/bitnami-docker-mariadb-galera#88]
### Name and Version

bitnmai/10.6.8-debian-11-r3

### What steps will reproduce the bug?

How can I enable ssl for the mysql port 3306?

So far I succeeded to secure the galera intra cluster traffic setting the ENV variable `MARIADB_ENABLE_TLS` but the port 3306 it seems to still be encrypted.

Reading the README.md (https://github.com/bitnami/bitnami-docker-mariadb-galera#securing-galera-cluster-traffic) it seems that it should be enough to set MARIADB_ENABLE_TLS,MARIADB_TLS_* variables and then use the following command to connect to mysql using ssl

`docker run -it --rm \
    -v /path/to/ca.pem:/bitnami/mariadb/certs/ca.pem:ro \
    --network app-tier \
    bitnami/mariadb-galera:latest mysql -h mariadb-galera -u root --ssl-ca=/bitnami/mariadb/certs/ca.pem`

but I can connect without setting the flag `-ssl-ca` and if I type the following command 

`openssl s_client -connect localhost:3306 | openssl x509 -text`

I does not show any certificate, while running the same command on the galera port (4567) it shows the certificate.

### What is the expected behavior?

Both port 3306 and 4567 should expose encrypted traffic with ssl

### What do you see instead?

only 4567 is encrypted and from the documentation (readme.md) it should be the case

**Comment by gongomgra** [comment]
Hi @fabry00,

Thanks for using Bitnami. I reproduced the issue you reported, but I think it is not related to Bitnami or how we build the images, as I also reproduced it in the official MariaDB image from Dockerhub.

```
$ docker run --name mariadb (... env configuration ...) mariadb:10.6.8
root@5210d608d630:/# apt-get install -y vim; vim /etc/mysql/mariadb.conf.d/50-server.cnf
root@5210d608d630:/# grep -C 5 "\[mariadb\]" /etc/mysql/mariadb.conf.d/50-server.cnf
[embedded]

# This group is only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]
ssl_cert = /bitnami/mariadb/certs/cert.pem
ssl_key = /bitnami/mariadb/certs/key.pem
ssl_ca = /bitnami/mariadb/certs/ca.pem
 
 (... perform container restart ...)
 
root@5210d608d630:/# mysql -u root -pbitnami123
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.6.8-MariaDB-1:10.6.8+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW VARIABLES LIKE '%ssl%';
+---------------------+---------------------------------+
| Variable_name       | Value                           |
+---------------------+---------------------------------+
| have_openssl        | YES                             |
| have_ssl            | YES                             |
| ssl_ca              | /bitnami/mariadb/certs/ca.pem   |
| ssl_capath          |                                 |
| ssl_cert            | /bitnami/mariadb/certs/cert.pem |
| ssl_cipher          |                                 |
| ssl_crl             |                                 |
| ssl_crlpath         |                                 |
| ssl_key             | /bitnami/mariadb/certs/key.pem  |
| version_ssl_library | OpenSSL 1.1.1f  31 Mar 2020     |
+---------------------+---------------------------------+
10 rows in set (0.001 sec)

MariaDB [(none)]> exit
Bye
root@5210d608d630:/# openssl s_client -connect localhost:3306
CONNECTED(00000003)
140248138327360:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 283 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

I get the same output configuring our image. Can you check it on your side?

**Comment by fmulero** [comment]
We are moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still facing this issue, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
